/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dell' at '17-6-18 下午2:37' with Gradle 2.11
 *
 * @author dell, @date 17-6-18 下午2:37
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
